In [2]:
import psycopg2
import psycopg2.extras
from pyvis.network import Network

In [3]:
conn = psycopg2.connect(user='postgres', database="postgres", password='password', host='localhost', port='5432')
cursor = conn.cursor(cursor_factory=psycopg2.extras.DictCursor)

In [4]:
cursor.execute('SELECT * FROM genre')

In [5]:
results = cursor.fetchall()
colnames = [desc[0] for desc in cursor.description]

In [6]:
genres = []
genres_id = {}
for genre in results:
    genres.append(genre[colnames.index('genre')])
    genres_id[genre[colnames.index('genre')]] = genre[colnames.index('genre_id')]

In [7]:
categories = {}
genres_assigned = []

keywords_basic = {
    'Pop': ['pop', 'alt z'], 
    'Rock': ['rock'], 
    'Classical': ['classical', 'cello', 'orchestra', 'baroque'], 
    'Jazz': ['jazz', 'bossa nova', 'big band', 'hard bop', 'bebop'], 
    'Blues': ['blues'], 
    'Folk': ['folk'], 
    'Funk': ['funk'], 
    'Lo-fi': ['lo-fi'], 
    'Indie': ['indie', 'alt z'], 
    'Metal': ['metal'], 
    'Hip hop': ['hip hop'], 
    'Edm': ['electronica', 'edm', 'house', 'moog', 'electronic', 'techno', 'vaporwave', 'tronica', 'dubstep', 'trance'],
    'Rap': ['rap'],
    'Soundtrack': ['soundtrack'],
    'Sertanejo': ['sertanejo'],
    'R&b': ['r&b', 'soul'],
    'Punk': ['punk'],
    'Reggae': ['reggae'],
    'Country': ['country'],
    'Instrumental': ['instrumental', 'ambient'],
    'Nacional': ['brasileiro', 'brazilian', 'brasileiros', 'brasileira', 'nacional'],
}

for keyword in keywords_basic.keys():
    categories[keyword] = []
    for genre in genres:
        for key in keywords_basic[keyword]:
            if key in genre:
                genres_assigned.append(genre)
                categories[keyword].append(genre)

print(len(list(set(genres) - set(genres_assigned))))

503

In [8]:
for category in categories:
    for genre in categories[category]:
        query = 'UPDATE genre SET genre_norm = \'' + category + '\' WHERE genre_id = ' + str(genres_id[genre])
        print(query)

UPDATE genre SET genre_norm = 'Pop' WHERE genre_id = 8
UPDATE genre SET genre_norm = 'Pop' WHERE genre_id = 9
UPDATE genre SET genre_norm = 'Pop' WHERE genre_id = 10
UPDATE genre SET genre_norm = 'Pop' WHERE genre_id = 11
UPDATE genre SET genre_norm = 'Pop' WHERE genre_id = 12
UPDATE genre SET genre_norm = 'Pop' WHERE genre_id = 14
UPDATE genre SET genre_norm = 'Pop' WHERE genre_id = 16
UPDATE genre SET genre_norm = 'Pop' WHERE genre_id = 18
UPDATE genre SET genre_norm = 'Pop' WHERE genre_id = 19
UPDATE genre SET genre_norm = 'Pop' WHERE genre_id = 20
UPDATE genre SET genre_norm = 'Pop' WHERE genre_id = 22
UPDATE genre SET genre_norm = 'Pop' WHERE genre_id = 23
UPDATE genre SET genre_norm = 'Pop' WHERE genre_id = 24
UPDATE genre SET genre_norm = 'Pop' WHERE genre_id = 25
UPDATE genre SET genre_norm = 'Pop' WHERE genre_id = 42
UPDATE genre SET genre_norm = 'Pop' WHERE genre_id = 62
UPDATE genre SET genre_norm = 'Pop' WHERE genre_id = 64
UPDATE genre SET genre_norm = 'Pop' WHERE genre_id = 68
UPDATE genre SET genre_norm = 'Pop' WHERE genre_id = 72
UPDATE genre SET genre_norm = 'Pop' WHERE genre_id = 73
UPDATE genre SET genre_norm = 'Pop' WHERE genre_id = 74
UPDATE genre SET genre_norm = 'Pop' WHERE genre_id = 75
UPDATE genre SET genre_norm = 'Pop' WHERE genre_id = 77
UPDATE genre SET genre_norm = 'Pop' WHERE genre_id = 78
UPDATE genre SET genre_norm = 'Pop' WHERE genre_id = 80
UPDATE genre SET genre_norm = 'Pop' WHERE genre_id = 81
UPDATE genre SET genre_norm = 'Pop' WHERE genre_id = 85
UPDATE genre SET genre_norm = 'Pop' WHERE genre_id = 86
UPDATE genre SET genre_norm = 'Pop' WHERE genre_id = 89
UPDATE genre SET genre_norm = 'Pop' WHERE genre_id = 96
UPDATE genre SET genre_norm = 'Pop' WHERE genre_id = 98
UPDATE genre SET genre_norm = 'Pop' WHERE genre_id = 100
UPDATE genre SET genre_norm = 'Pop' WHERE genre_id = 103
UPDATE genre SET genre_norm = 'Pop' WHERE genre_id = 107
UPDATE genre SET genre_norm = 'Pop' WHERE genre_id = 108
UPDATE genre SET genre_norm = 'Pop' WHERE genre_id = 109
UPDATE genre SET genre_norm = 'Pop' WHERE genre_id = 112
UPDATE genre SET genre_norm = 'Pop' WHERE genre_id = 114
UPDATE genre SET genre_norm = 'Pop' WHERE genre_id = 116
UPDATE genre SET genre_norm = 'Pop' WHERE genre_id = 118
UPDATE genre SET genre_norm = 'Pop' WHERE genre_id = 119
UPDATE genre SET genre_norm = 'Pop' WHERE genre_id = 120
UPDATE genre SET genre_norm = 'Pop' WHERE genre_id = 126
UPDATE genre SET genre_norm = 'Pop' WHERE genre_id = 128
UPDATE genre SET genre_norm = 'Pop' WHERE genre_id = 133
UPDATE genre SET genre_norm = 'Pop' WHERE genre_id = 141
UPDATE genre SET genre_norm = 'Pop' WHERE genre_id = 147
UPDATE genre SET genre_norm = 'Pop' WHERE genre_id = 148
UPDATE genre SET genre_norm = 'Pop' WHERE genre_id = 150
UPDATE genre SET genre_norm = 'Pop' WHERE genre_id = 159
UPDATE genre SET genre_norm = 'Pop' WHERE genre_id = 170
UPDATE genre SET genre_norm = 'Pop' WHERE genre_id = 190
UPDATE genre SET genre_norm = 'Pop' WHERE genre_id = 191
UPDATE genre SET genre_norm = 'Pop' WHERE genre_id = 194
UPDATE genre SET genre_norm = 'Pop' WHERE genre_id = 207
UPDATE genre SET genre_norm = 'Pop' WHERE genre_id = 214
UPDATE genre SET genre_norm = 'Pop' WHERE genre_id = 234
UPDATE genre SET genre_norm = 'Pop' WHERE genre_id = 243
UPDATE genre SET genre_norm = 'Pop' WHERE genre_id = 246
UPDATE genre SET genre_norm = 'Pop' WHERE genre_id = 247
UPDATE genre SET genre_norm = 'Pop' WHERE genre_id = 251
UPDATE genre SET genre_norm = 'Pop' WHERE genre_id = 260
UPDATE genre SET genre_norm = 'Pop' WHERE genre_id = 285
UPDATE genre SET genre_norm = 'Pop' WHERE genre_id = 288
UPDATE genre SET genre_norm = 'Pop' WHERE genre_id = 293
UPDATE genre SET genre_norm = 'Pop' WHERE genre_id = 316
UPDATE genre SET genre_norm = 'Pop' WHERE genre_id = 327
UPDATE genre SET genre_norm = 'Pop' WHERE genre_id = 328
UPDATE genre SET genre_norm = 'Pop' WHERE genre_id = 337
UPDATE genre SET genre_norm = 'Pop' WHERE genre_id = 351
UPDATE genre SET genre_norm = 'Pop' WHERE genre_id = 362
UPDATE genre SET genre_norm = 'Pop' WHERE genre_id = 367
UPDATE genre SET genre_norm = 'Pop' WHERE genre_id = 372
UPDATE genre SET genre_norm = 'Pop' WHERE genre_id = 375
UPDATE genre SET genre_norm = 'Pop' WHERE genre_id = 394
UPDATE genre SET genre_norm = 'Pop' WHERE genre_id = 467
UPDATE genre SET genre_norm = 'Pop' WHERE genre_id = 475
UPDATE genre SET genre_norm = 'Pop' WHERE genre_id = 476
UPDATE genre SET genre_norm = 'Pop' WHERE genre_id = 478
UPDATE genre SET genre_norm = 'Pop' WHERE genre_id = 485
UPDATE genre SET genre_norm = 'Pop' WHERE genre_id = 491
UPDATE genre SET genre_norm = 'Pop' WHERE genre_id = 495
UPDATE genre SET genre_norm = 'Pop' WHERE genre_id = 504
UPDATE genre SET genre_norm = 'Pop' WHERE genre_id = 506
UPDATE genre SET genre_norm = 'Pop' WHERE genre_id = 507
UPDATE genre SET genre_norm = 'Pop' WHERE genre_id = 546
UPDATE genre SET genre_norm = 'Pop' WHERE genre_id = 569
UPDATE genre SET genre_norm = 'Pop' WHERE genre_id = 570
UPDATE genre SET genre_norm = 'Pop' WHERE genre_id = 586
UPDATE genre SET genre_norm = 'Pop' WHERE genre_id = 591
UPDATE genre SET genre_norm = 'Pop' WHERE genre_id = 592
UPDATE genre SET genre_norm = 'Pop' WHERE genre_id = 593
UPDATE genre SET genre_norm = 'Pop' WHERE genre_id = 598
UPDATE genre SET genre_norm = 'Pop' WHERE genre_id = 613
UPDATE genre SET genre_norm = 'Pop' WHERE genre_id = 638
UPDATE genre SET genre_norm = 'Pop' WHERE genre_id = 645
UPDATE genre SET genre_norm = 'Pop' WHERE genre_id = 646
UPDATE genre SET genre_norm = 'Pop' WHERE genre_id = 649
UPDATE genre SET genre_norm = 'Pop' WHERE genre_id = 659
UPDATE genre SET genre_norm = 'Pop' WHERE genre_id = 669
UPDATE genre SET genre_norm = 'Pop' WHERE genre_id = 716
UPDATE genre SET genre_norm = 'Pop' WHERE genre_id = 723
UPDATE genre SET genre_norm = 'Pop' WHERE genre_id = 729
UPDATE genre SET genre_norm = 'Pop' WHERE genre_id = 732
UPDATE genre SET genre_norm = 'Pop' WHERE genre_id = 734
UPDATE genre SET genre_norm = 'Pop' WHERE genre_id = 750
UPDATE genre SET genre_norm = 'Pop' WHERE genre_id = 758
UPDATE genre SET genre_norm = 'Pop' WHERE genre_id = 759
UPDATE genre SET genre_norm = 'Pop' WHERE genre_id = 760
UPDATE genre SET genre_norm = 'Pop' WHERE genre_id = 767
UPDATE genre SET genre_norm = 'Pop' WHERE genre_id = 789
UPDATE genre SET genre_norm = 'Pop' WHERE genre_id = 790
UPDATE genre SET genre_norm = 'Pop' WHERE genre_id = 791
UPDATE genre SET genre_norm = 'Pop' WHERE genre_id = 798
UPDATE genre SET genre_norm = 'Pop' WHERE genre_id = 814
UPDATE genre SET genre_norm = 'Pop' WHERE genre_id = 815
UPDATE genre SET genre_norm = 'Pop' WHERE genre_id = 817
UPDATE genre SET genre_norm = 'Pop' WHERE genre_id = 819
UPDATE genre SET genre_norm = 'Pop' WHERE genre_id = 827
UPDATE genre SET genre_norm = 'Pop' WHERE genre_id = 839
UPDATE genre SET genre_norm = 'Pop' WHERE genre_id = 846
UPDATE genre SET genre_norm = 'Pop' WHERE genre_id = 849
UPDATE genre SET genre_norm = 'Pop' WHERE genre_id = 859
UPDATE genre SET genre_norm = 'Pop' WHERE genre_id = 862
UPDATE genre SET genre_norm = 'Pop' WHERE genre_id = 869
UPDATE genre SET genre_norm = 'Pop' WHERE genre_id = 880
UPDATE genre SET genre_norm = 'Pop' WHERE genre_id = 887
UPDATE genre SET genre_norm = 'Pop' WHERE genre_id = 888
UPDATE genre SET genre_norm = 'Pop' WHERE genre_id = 889
UPDATE genre SET genre_norm = 'Pop' WHERE genre_id = 893
UPDATE genre SET genre_norm = 'Pop' WHERE genre_id = 909
UPDATE genre SET genre_norm = 'Pop' WHERE genre_id = 918
UPDATE genre SET genre_norm = 'Pop' WHERE genre_id = 919
UPDATE genre SET genre_norm = 'Pop' WHERE genre_id = 929
UPDATE genre SET genre_norm = 'Pop' WHERE genre_id = 936
UPDATE genre SET genre_norm = 'Pop' WHERE genre_id = 956
UPDATE genre SET genre_norm = 'Pop' WHERE genre_id = 961
UPDATE genre SET genre_norm = 'Pop' WHERE genre_id = 964
UPDATE genre SET genre_norm = 'Pop' WHERE genre_id = 976
UPDATE genre SET genre_norm = 'Pop' WHERE genre_id = 979
UPDATE genre SET genre_norm = 'Pop' WHERE genre_id = 985
UPDATE genre SET genre_norm = 'Pop' WHERE genre_id = 995
UPDATE genre SET genre_norm = 'Pop' WHERE genre_id = 1023
UPDATE genre SET genre_norm = 'Pop' WHERE genre_id = 1057
UPDATE genre SET genre_norm = 'Pop' WHERE genre_id = 1146
UPDATE genre SET genre_norm = 'Pop' WHERE genre_id = 1149
UPDATE genre SET genre_norm = 'Pop' WHERE genre_id = 1151
UPDATE genre SET genre_norm = 'Pop' WHERE genre_id = 1159
UPDATE genre SET genre_norm = 'Pop' WHERE genre_id = 1161
UPDATE genre SET genre_norm = 'Pop' WHERE genre_id = 1199
UPDATE genre SET genre_norm = 'Pop' WHERE genre_id = 1206
UPDATE genre SET genre_norm = 'Pop' WHERE genre_id = 1207
UPDATE genre SET genre_norm = 'Pop' WHERE genre_id = 1221
UPDATE genre SET genre_norm = 'Pop' WHERE genre_id = 1247
UPDATE genre SET genre_norm = 'Pop' WHERE genre_id = 1259
UPDATE genre SET genre_norm = 'Pop' WHERE genre_id = 1272
UPDATE genre SET genre_norm = 'Pop' WHERE genre_id = 1288
UPDATE genre SET genre_norm = 'Pop' WHERE genre_id = 1299
UPDATE genre SET genre_norm = 'Pop' WHERE genre_id = 1312
UPDATE genre SET genre_norm = 'Pop' WHERE genre_id = 1317
UPDATE genre SET genre_norm = 'Pop' WHERE genre_id = 1329
UPDATE genre SET genre_norm = 'Pop' WHERE genre_id = 1335
UPDATE genre SET genre_norm = 'Pop' WHERE genre_id = 1341
UPDATE genre SET genre_norm = 'Pop' WHERE genre_id = 1348
UPDATE genre SET genre_norm = 'Pop' WHERE genre_id = 1355
UPDATE genre SET genre_norm = 'Pop' WHERE genre_id = 1357
UPDATE genre SET genre_norm = 'Pop' WHERE genre_id = 1358
UPDATE genre SET genre_norm = 'Pop' WHERE genre_id = 1359
UPDATE genre SET genre_norm = 'Pop' WHERE genre_id = 1376
UPDATE genre SET genre_norm = 'Pop' WHERE genre_id = 1406
UPDATE genre SET genre_norm = 'Pop' WHERE genre_id = 1408
UPDATE genre SET genre_norm = 'Pop' WHERE genre_id = 1437
UPDATE genre SET genre_norm = 'Pop' WHERE genre_id = 1442
UPDATE genre SET genre_norm = 'Pop' WHERE genre_id = 1447
UPDATE genre SET genre_norm = 'Pop' WHERE genre_id = 1454
UPDATE genre SET genre_norm = 'Pop' WHERE genre_id = 1463
UPDATE genre SET genre_norm = 'Pop' WHERE genre_id = 1478
UPDATE genre SET genre_norm = 'Pop' WHERE genre_id = 1503
UPDATE genre SET genre_norm = 'Pop' WHERE genre_id = 1504
UPDATE genre SET genre_norm = 'Pop' WHERE genre_id = 1524
UPDATE genre SET genre_norm = 'Pop' WHERE genre_id = 1525
UPDATE genre SET genre_norm = 'Pop' WHERE genre_id = 1548
UPDATE genre SET genre_norm = 'Pop' WHERE genre_id = 1554
UPDATE genre SET genre_norm = 'Pop' WHERE genre_id = 1567
UPDATE genre SET genre_norm = 'Pop' WHERE genre_id = 1568
UPDATE genre SET genre_norm = 'Pop' WHERE genre_id = 1569
UPDATE genre SET genre_norm = 'Rock' WHERE genre_id = 2
UPDATE genre SET genre_norm = 'Rock' WHERE genre_id = 6
UPDATE genre SET genre_norm = 'Rock' WHERE genre_id = 19
UPDATE genre SET genre_norm = 'Rock' WHERE genre_id = 32
UPDATE genre SET genre_norm = 'Rock' WHERE genre_id = 33
UPDATE genre SET genre_norm = 'Rock' WHERE genre_id = 34
UPDATE genre SET genre_norm = 'Rock' WHERE genre_id = 35
UPDATE genre SET genre_norm = 'Rock' WHERE genre_id = 36
UPDATE genre SET genre_norm = 'Rock' WHERE genre_id = 45
UPDATE genre SET genre_norm = 'Rock' WHERE genre_id = 54
UPDATE genre SET genre_norm = 'Rock' WHERE genre_id = 94
UPDATE genre SET genre_norm = 'Rock' WHERE genre_id = 96
UPDATE genre SET genre_norm = 'Rock' WHERE genre_id = 97
UPDATE genre SET genre_norm = 'Rock' WHERE genre_id = 130
UPDATE genre SET genre_norm = 'Rock' WHERE genre_id = 131
UPDATE genre SET genre_norm = 'Rock' WHERE genre_id = 143
UPDATE genre SET genre_norm = 'Rock' WHERE genre_id = 153
UPDATE genre SET genre_norm = 'Rock' WHERE genre_id = 162
UPDATE genre SET genre_norm = 'Rock' WHERE genre_id = 163
UPDATE genre SET genre_norm = 'Rock' WHERE genre_id = 168
UPDATE genre SET genre_norm = 'Rock' WHERE genre_id = 171
UPDATE genre SET genre_norm = 'Rock' WHERE genre_id = 173
UPDATE genre SET genre_norm = 'Rock' WHERE genre_id = 206
UPDATE genre SET genre_norm = 'Rock' WHERE genre_id = 210
UPDATE genre SET genre_norm = 'Rock' WHERE genre_id = 211
UPDATE genre SET genre_norm = 'Rock' WHERE genre_id = 215
UPDATE genre SET genre_norm = 'Rock' WHERE genre_id = 216
UPDATE genre SET genre_norm = 'Rock' WHERE genre_id = 223
UPDATE genre SET genre_norm = 'Rock' WHERE genre_id = 227
UPDATE genre SET genre_norm = 'Rock' WHERE genre_id = 254
UPDATE genre SET genre_norm = 'Rock' WHERE genre_id = 255
UPDATE genre SET genre_norm = 'Rock' WHERE genre_id = 265
UPDATE genre SET genre_norm = 'Rock' WHERE genre_id = 266
UPDATE genre SET genre_norm = 'Rock' WHERE genre_id = 267
UPDATE genre SET genre_norm = 'Rock' WHERE genre_id = 268
UPDATE genre SET genre_norm = 'Rock' WHERE genre_id = 269
UPDATE genre SET genre_norm = 'Rock' WHERE genre_id = 289
UPDATE genre SET genre_norm = 'Rock' WHERE genre_id = 295
UPDATE genre SET genre_norm = 'Rock' WHERE genre_id = 302
UPDATE genre SET genre_norm = 'Rock' WHERE genre_id = 305
UPDATE genre SET genre_norm = 'Rock' WHERE genre_id = 307
UPDATE genre SET genre_norm = 'Rock' WHERE genre_id = 331
UPDATE genre SET genre_norm = 'Rock' WHERE genre_id = 398
UPDATE genre SET genre_norm = 'Rock' WHERE genre_id = 399
UPDATE genre SET genre_norm = 'Rock' WHERE genre_id = 453
UPDATE genre SET genre_norm = 'Rock' WHERE genre_id = 481
UPDATE genre SET genre_norm = 'Rock' WHERE genre_id = 509
UPDATE genre SET genre_norm = 'Rock' WHERE genre_id = 538
UPDATE genre SET genre_norm = 'Rock' WHERE genre_id = 542
UPDATE genre SET genre_norm = 'Rock' WHERE genre_id = 548
UPDATE genre SET genre_norm = 'Rock' WHERE genre_id = 564
UPDATE genre SET genre_norm = 'Rock' WHERE genre_id = 565
UPDATE genre SET genre_norm = 'Rock' WHERE genre_id = 566
UPDATE genre SET genre_norm = 'Rock' WHERE genre_id = 594
UPDATE genre SET genre_norm = 'Rock' WHERE genre_id = 610
UPDATE genre SET genre_norm = 'Rock' WHERE genre_id = 632
UPDATE genre SET genre_norm = 'Rock' WHERE genre_id = 653
UPDATE genre SET genre_norm = 'Rock' WHERE genre_id = 661
UPDATE genre SET genre_norm = 'Rock' WHERE genre_id = 666
UPDATE genre SET genre_norm = 'Rock' WHERE genre_id = 680
UPDATE genre SET genre_norm = 'Rock' WHERE genre_id = 681
UPDATE genre SET genre_norm = 'Rock' WHERE genre_id = 695
UPDATE genre SET genre_norm = 'Rock' WHERE genre_id = 762
UPDATE genre SET genre_norm = 'Rock' WHERE genre_id = 777
UPDATE genre SET genre_norm = 'Rock' WHERE genre_id = 783
UPDATE genre SET genre_norm = 'Rock' WHERE genre_id = 835
UPDATE genre SET genre_norm = 'Rock' WHERE genre_id = 838
UPDATE genre SET genre_norm = 'Rock' WHERE genre_id = 871
UPDATE genre SET genre_norm = 'Rock' WHERE genre_id = 930
UPDATE genre SET genre_norm = 'Rock' WHERE genre_id = 940
UPDATE genre SET genre_norm = 'Rock' WHERE genre_id = 941
UPDATE genre SET genre_norm = 'Rock' WHERE genre_id = 944
UPDATE genre SET genre_norm = 'Rock' WHERE genre_id = 946
UPDATE genre SET genre_norm = 'Rock' WHERE genre_id = 947
UPDATE genre SET genre_norm = 'Rock' WHERE genre_id = 949
UPDATE genre SET genre_norm = 'Rock' WHERE genre_id = 975
UPDATE genre SET genre_norm = 'Rock' WHERE genre_id = 982
UPDATE genre SET genre_norm = 'Rock' WHERE genre_id = 983
UPDATE genre SET genre_norm = 'Rock' WHERE genre_id = 990
UPDATE genre SET genre_norm = 'Rock' WHERE genre_id = 994
UPDATE genre SET genre_norm = 'Rock' WHERE genre_id = 1024
UPDATE genre SET genre_norm = 'Rock' WHERE genre_id = 1045
UPDATE genre SET genre_norm = 'Rock' WHERE genre_id = 1050
UPDATE genre SET genre_norm = 'Rock' WHERE genre_id = 1067
UPDATE genre SET genre_norm = 'Rock' WHERE genre_id = 1071
UPDATE genre SET genre_norm = 'Rock' WHERE genre_id = 1099
UPDATE genre SET genre_norm = 'Rock' WHERE genre_id = 1116
UPDATE genre SET genre_norm = 'Rock' WHERE genre_id = 1123
UPDATE genre SET genre_norm = 'Rock' WHERE genre_id = 1125
UPDATE genre SET genre_norm = 'Rock' WHERE genre_id = 1126
UPDATE genre SET genre_norm = 'Rock' WHERE genre_id = 1127
UPDATE genre SET genre_norm = 'Rock' WHERE genre_id = 1148
UPDATE genre SET genre_norm = 'Rock' WHERE genre_id = 1151
UPDATE genre SET genre_norm = 'Rock' WHERE genre_id = 1168
UPDATE genre SET genre_norm = 'Rock' WHERE genre_id = 1169
UPDATE genre SET genre_norm = 'Rock' WHERE genre_id = 1170
UPDATE genre SET genre_norm = 'Rock' WHERE genre_id = 1171
UPDATE genre SET genre_norm = 'Rock' WHERE genre_id = 1223
UPDATE genre SET genre_norm = 'Rock' WHERE genre_id = 1229
UPDATE genre SET genre_norm = 'Rock' WHERE genre_id = 1248
UPDATE genre SET genre_norm = 'Rock' WHERE genre_id = 1265
UPDATE genre SET genre_norm = 'Rock' WHERE genre_id = 1302
UPDATE genre SET genre_norm = 'Rock' WHERE genre_id = 1320
UPDATE genre SET genre_norm = 'Rock' WHERE genre_id = 1325
UPDATE genre SET genre_norm = 'Rock' WHERE genre_id = 1326
UPDATE genre SET genre_norm = 'Rock' WHERE genre_id = 1352
UPDATE genre SET genre_norm = 'Rock' WHERE genre_id = 1353
UPDATE genre SET genre_norm = 'Rock' WHERE genre_id = 1362
UPDATE genre SET genre_norm = 'Rock' WHERE genre_id = 1366
UPDATE genre SET genre_norm = 'Rock' WHERE genre_id = 1369
UPDATE genre SET genre_norm = 'Rock' WHERE genre_id = 1373
UPDATE genre SET genre_norm = 'Rock' WHERE genre_id = 1401
UPDATE genre SET genre_norm = 'Rock' WHERE genre_id = 1402
UPDATE genre SET genre_norm = 'Rock' WHERE genre_id = 1411
UPDATE genre SET genre_norm = 'Rock' WHERE genre_id = 1429
UPDATE genre SET genre_norm = 'Rock' WHERE genre_id = 1431
UPDATE genre SET genre_norm = 'Rock' WHERE genre_id = 1434
UPDATE genre SET genre_norm = 'Rock' WHERE genre_id = 1459
UPDATE genre SET genre_norm = 'Rock' WHERE genre_id = 1465
UPDATE genre SET genre_norm = 'Rock' WHERE genre_id = 1483
UPDATE genre SET genre_norm = 'Rock' WHERE genre_id = 1487
UPDATE genre SET genre_norm = 'Rock' WHERE genre_id = 1493
UPDATE genre SET genre_norm = 'Rock' WHERE genre_id = 1511
UPDATE genre SET genre_norm = 'Rock' WHERE genre_id = 1528
UPDATE genre SET genre_norm = 'Rock' WHERE genre_id = 1532
UPDATE genre SET genre_norm = 'Rock' WHERE genre_id = 1535
UPDATE genre SET genre_norm = 'Rock' WHERE genre_id = 1577
UPDATE genre SET genre_norm = 'Classical' WHERE genre_id = 190
UPDATE genre SET genre_norm = 'Classical' WHERE genre_id = 231
UPDATE genre SET genre_norm = 'Classical' WHERE genre_id = 241
UPDATE genre SET genre_norm = 'Classical' WHERE genre_id = 270
UPDATE genre SET genre_norm = 'Classical' WHERE genre_id = 271
UPDATE genre SET genre_norm = 'Classical' WHERE genre_id = 274
UPDATE genre SET genre_norm = 'Classical' WHERE genre_id = 275
UPDATE genre SET genre_norm = 'Classical' WHERE genre_id = 276
UPDATE genre SET genre_norm = 'Classical' WHERE genre_id = 277
UPDATE genre SET genre_norm = 'Classical' WHERE genre_id = 320
UPDATE genre SET genre_norm = 'Classical' WHERE genre_id = 377
UPDATE genre SET genre_norm = 'Classical' WHERE genre_id = 411
UPDATE genre SET genre_norm = 'Classical' WHERE genre_id = 413
UPDATE genre SET genre_norm = 'Classical' WHERE genre_id = 414
UPDATE genre SET genre_norm = 'Classical' WHERE genre_id = 415
UPDATE genre SET genre_norm = 'Classical' WHERE genre_id = 416
UPDATE genre SET genre_norm = 'Classical' WHERE genre_id = 436
UPDATE genre SET genre_norm = 'Classical' WHERE genre_id = 440
UPDATE genre SET genre_norm = 'Classical' WHERE genre_id = 441
UPDATE genre SET genre_norm = 'Classical' WHERE genre_id = 442
UPDATE genre SET genre_norm = 'Classical' WHERE genre_id = 444
UPDATE genre SET genre_norm = 'Classical' WHERE genre_id = 614
UPDATE genre SET genre_norm = 'Classical' WHERE genre_id = 615
UPDATE genre SET genre_norm = 'Classical' WHERE genre_id = 616
UPDATE genre SET genre_norm = 'Classical' WHERE genre_id = 617
UPDATE genre SET genre_norm = 'Classical' WHERE genre_id = 618
UPDATE genre SET genre_norm = 'Classical' WHERE genre_id = 672
UPDATE genre SET genre_norm = 'Classical' WHERE genre_id = 674
UPDATE genre SET genre_norm = 'Classical' WHERE genre_id = 682
UPDATE genre SET genre_norm = 'Classical' WHERE genre_id = 712
UPDATE genre SET genre_norm = 'Classical' WHERE genre_id = 714

In [9]:
list(set(genres) - set(genres_assigned))

['rave',
 'lds youth',
 'shoegaze',
 'nz singer-songwriter',
 'modular synth',
 'german dance',
 'samba moderno',
 'italian opera',
 'bachata',
 'australian experimental',
 'sunnlensk tonlist',
 'shimmer psych',
 'speed garage',
 'parody',
 'worship',
 'british choir',
 'late romantic era',
 'french psychedelic',
 'fluxwork',
 'grave wave',
 'german prog',
 'jawaiian',
 'lilith',
 'oud',
 'british comedy',
 'melbourne bounce international',
 'big room',
 'nz christian',
 'dixieland',
 'complextro',
 'alternative ccm',
 'big beat',
 'australian psych',
 'chillwave',
 'stride',
 'japanese beats',
 'meditation',
 'perreo',
 'doo-wop',
 'talent show',
 'italian tenor',
 'nouvelle chanson francaise',
 'melbourne bounce',
 'israeli singer-songwriter',
 'new rave',
 'exotica',
 'chillstep',
 'old-time',
 'downtempo bass',
 'ccm',
 'experimental',
 'plunderphonics',
 'japanese chillhop',
 'partido alto',
 'middle earth',
 'turntablism',
 'bboy',
 'experimental guitar',
 'symfonicky orchestr',
 'russian dance',
 'native american',
 'musica crista reformada',
 'supergroup',
 'melodic thrash',
 'environmental',
 'belgian dance',
 'scorecore',
 'nova mpb',
 'world meditation',
 'grindcore',
 'praise',
 'breakbeat',
 'new england americana',
 'post-disco',
 'samba',
 'drone',
 'black comedy',
 'waiata maori',
 'new age piano',
 'gamecore',
 'latino comedy',
 'future bass',
 'viola',
 'enka',
 'contemporary post-bop',
 'sky room',
 'plugg',
 'solipsynthm',
 'lute',
 'irish singer-songwriter',
 'synthwave',
 'tzadik',
 'neoclassicism',
 'sound',
 'synthesizer',
 'pagode baiano',
 'permanent wave',
 'nova musica pernambucana',
 'movie tunes',
 'merseybeat',
 'new americana',
 'video game music',
 'chill out',
 'afrobeat',
 'dancefloor dnb',
 'latin alternative',
 'francoton',
 'russian romanticism',
 'mandolin',
 'tin pan alley',
 'canzone napoletana',
 'nashville singer-songwriter',
 'minecraft',
 'azonto',
 'electric bass',
 'british invasion',
 'japanese vgm',
 'wave',
 'phonk',
 'christelijk',
 'ambeat',
 'focus',
 'pixie',
 'classic girl group',
 'world worship',
 'acousmatic',
 'musica portuguesa contemporanea',
 'abstract idm',
 'alternative americana',
 'choro contemporaneo',
 'shibuya-kei',
 'musica infantil',
 'acoustic chill',
 'eurodance',
 'steel guitar',
 'laboratorio',
 'escape room',
 'uk dancehall',
 'modern electroacoustic',
 'glitchcore',
 'shush',
 'eurovision',
 'old-time fiddle',
 'new tribe',
 'world chill',
 'italian bass',
 'power noise',
 'musica andina',
 'post-romantic era',
 'historic piano performance',
 "women's music",
 'samba de roda',
 'post-screamo',
 'jersey club',
 'early romantic era',
 'musica para criancas',
 'choro',
 'boogaloo',
 'disney russian',
 'drill and bass',
 'broadway',
 'musica baiana',
 'downtempo',
 'jump up',
 'musica juiz-forana',
 'theme',
 'harpsichord',
 'auteur-compositeur-interprete quebecois',
 'a cappella',
 'canadian americana',
 'dark wave',
 'art song',
 'bassline',
 'waiata mo tamariki',
 'electra',
 'horror synth',
 'mbalax',
 'chill guitar',
 'circuit',
 'midwest americana',
 'intelligent dance music',
 'family gospel',
 'salsa',
 'dark clubbing',
 'rain',
 'j-idol',
 'focus beats',
 'banjo',
 'manguebeat',
 'musica alagoana',
 'native american contemporary',
 'free improvisation',
 'jam band',
 'variete francaise',
 'anime score',
 'wonky',
 'crunk',
 'weightless',
 'piano mpb',
 'old school dancehall',
 'drill',
 'post-hardcore',
 'fake',
 'halftime dnb',
 'japanese new wave',
 'victorian britain',
 'balearic',
 'neo-progressive',
 'screamo',
 'western americana',
 'ninja',
 'boogie-woogie',
 'demoscene',
 'latin',
 'musica catarinense',
 'musica cearense',
 'latin afrobeat',
 'chilean hardcore',
 'swedish singer-songwriter',
 'second line',
 'german opera',
 'contrabass',
 'swancore',
 'girl group',
 'electroclash',
 'neo-kraut',
 'dutch dnb',
 'forro tradicional',
 'footwork',
 'tipico',
 'glitch',
 'neo-singer-songwriter',
 'ethereal wave',
 'boy band',
 'australian talent show',
 'cuban alternative',
 'background music',
 'trip hop',
 'chill beats',
 'new wave',
 'chillhop',
 'kawaii future bass',
 'radio symphony',
 'post-minimalism',
 'comic',
 'guitarra clasica',
 'balkan beats',
 'forro',
 'industrial',
 'musique peule',
 'new weird america',
 'flamenco',
 'basshall',
 'hauntology',
 'sleep',
 'grunge',
 'stomp and flutter',
 'musica potiguar',
 'afro dancehall',
 'vgm remix',
 'south african alternative',
 'roda de samba',
 'riddim',
 'kora',
 'samba-enredo',
 'italo dance',
 'american choir',
 'cosmic american',
 'freestyle',
 'brass band',
 'urbano espanol',
 'world devotional',
 'brostep',
 'afrofuturism',
 'singer-songwriter',
 'cathedral choir',
 'new french touch',
 'hammond organ',
 'bandolim',
 'motown',
 'slowcore',
 'doomcore',
 'palm desert scene',
 'wrestling',
 'deep big room',
 'chanson',
 'musica para ninos',
 'canterbury scene',
 'easy listening',
 'afro-cuban percussion',
 'french romanticism',
 'quiet storm',
 'violao',
 'idol',
 'italian romanticism',
 'dancehall',
 'modern performance',
 'adult standards',
 'italian occult psychedelia',
 'darksynth',
 'relaxative',
 'deconstructed club',
 'electro',
 'vocaloid',
 'dream smp',
 'purple sound',
 'rumba',
 'nu disco',
 'post-grunge',
 'mellow gold',
 'jovem guarda',
 'dreamo',
 'mashup',
 'hip-hop experimental',
 'nu age',
 'mpb',
 'pagode',
 'hollywood',
 'french opera',
 'atmosphere',
 'minimalism',
 'soca',
 'icelandic singer-songwriter',
 'show tunes',
 'festigal',
 'nu skool breaks',
 'bornesange',
 'glitch hop',
 'disney',
 'beatlesque',
 'gqom',
 'german romanticism',
 'barnmusik',
 'world',
 'nova musica carioca',
 'tecnobrega',
 'bluegrass',
 'fado',
 'shred',
 'broken beat',
 'baithak gana',
 'future garage',
 'nashville sound',
 'gothic americana',
 'doomgaze',
 'nashville americana',
 'pagode novo',
 'axe',
 'gospel',
 'quatuor a cordes',
 'canadian ccm',
 'bubblegum dance',
 'harlem renaissance',
 'urban contemporary',
 'hawaiian',
 'australian americana',
 'experimental synth',
 'new jack swing',
 'minimal dub',
 'drum and bass',
 'bmore',
 'nightrun',
 'choral',
 'afroswing',
 'nova musica paulista',
 'recorder',
 'american primitive',
 'tropical',
 'swedish experimental',
 'musica maranhense',
 'vapor twitch',
 'north carolina roots',
 'zouk riddim',
 'christian dance',
 'fingerstyle',
 'french shoegaze',
 'modern salsa',
 'opera',
 'berlin school',
 'marching band',
 'electrofox',
 'impressionism',
 'chamber psych',
 'world fusion',
 'early music ensemble',
 'electro latino',
 'deep freestyle',
 'austin americana',
 'groove room',
 'australian indigenous',
 'piano cover',
 'sovietwave',
 'musica londrinense',
 'neo mellow',
 'historically informed performance',
 'hi-nrg',
 'stomp and holler',
 'lounge',
 'comedy',
 'japanese singer-songwriter',
 'uk dnb',
 'smooth saxophone',
 'psychedelic doom',
 'musica de fondo',
 'italian experimental',
 'classify',
 'hopebeat',
 'drift',
 'musical advocacy',
 'scottish singer-songwriter',
 'vogue',
 'mallet',
 'velha guarda',
 'otacore',
 'roots americana',
 'new age',
 'dakke dak',
 'hardvapour',
 'salon music',
 'swing',
 'neo-psychedelic',
 'substep',
 'christian a cappella',
 'spacewave',
 'string quartet',
 'electro swing',
 'progressive bluegrass',
 'kenyan alternative',
 'christian music',
 'griot',
 'tribute',
 'skansk musik',
 'early music',
 'uk americana',
 'norwegian singer-songwriter',
 'russian ccm',
 'alternative dance',
 'library music',
 'c64',
 'bass music',
 'background piano',
 'mambo',
 'canadian singer-songwriter',
 'musique mandingue',
 'coverchill',
 'musica sul-mato-grossense',
 'batidao romantico',
 'early avant garde',
 'musica paranaense',
 'avant-garde',
 'old school thrash',
 'jungle',
 'brega romantico',
 'ritmo kombina',
 'forro de favela',
 'zolo',
 'violin',
 'chicago bop',
 'new comedy',
 'uk dance',
 'adoracao',
 'bubblegrunge',
 'sacred steel',
 'moombahton',
 'australian singer-songwriter',
 'piseiro',
 'spirituals',
 'comedienne',
 'disco',
 'australian dance',
 'double drumming',
 'pianissimo',
 'salsa puertorriquena',
 'deep idm',
 'disney portugues brasil',
 'redneck',
 'dub',
 'military band',
 'electro dub',
 'british singer-songwriter',
 'filthstep',
 'melancholia',
 'torch song',
 'new romantic',
 'tropicalia',
 'fourth world',
 'speedrun',
 'latin talent show',
 'serialism',
 'madchester',
 'boom bap',
 'birmingham grime',
 'grime',
 'minimal dnb',
 'epicore',
 'ska',
 'asmr',
 'deep new americana',
 'emo',
 'umbanda',
 'louvor',
 'progressive post-hardcore',
 'musica rondoniense']

In [10]:
categories.keys()

dict_keys(['Pop', 'Rock', 'Classical', 'Jazz', 'Blues', 'Folk', 'Funk', 'Lo-fi', 'Indie', 'Metal', 'Hip hop', 'Edm', 'Rap', 'Soundtrack', 'Sertanejo', 'R&b', 'Punk', 'Reggae', 'Country', 'Instrumental', 'Nacional'])

In [11]:
net = Network(notebook=True)
net.add_node('Genres')
net.add_nodes(list(categories.keys()), size=[15] * len(list(categories.keys())))
for category in categories:
    net.add_edge('Genres', category)
    net.add_nodes(categories[category], size=[5] * len(categories[category]))
    for item in categories[category]:
        net.add_edge(category, item)

In [12]:
net.show_buttons(filter_=['physics'])
net.show('mygraph.html')